      PROGRAM CONTROL !(INPUT,OUTPUT,TAPE 60=INPUT)
C     NELM=NUMBER OF DISCRETE ELEMENTS IN THE FEEDLINE, I. E. LINES,
C     BELLOWS, PVC JOINTS, ETC.
C     NELM INTEGER CONSTANTS ARE READ IN AND DESCRIBE THE TYPE OF 
C     ELEMENTS IN THE ORDER THEY APPEAR IN THE LINE BEGINNING AT THE 
C     OUTPUT OF THE FUEL TANK AND TERMINATED WITH THE COMBINED INPUT
C     IMPEDANCE TO THE TURBOPUMP, INGECTOR AND ENGINE. FOR EXAMPLE,
C     ITYPE(J)=M, J=ELEMENT NUMBER, M=ELEMENT TYPE
C     M=1 SIMPLE LINE WITH NO EXTERNAL EXITATION
C     M=2 CAVITATION BUBBLE
C     M=3 PRESSURE VOLUME COMPENSATOR
C     M=4 SIDE BRUNCH PULSER
C     M=5 RIGID BODY MOTION OF A SIMPLE LINE, VELOCITY EXCITATION
C     M=6 NPAR LINES IN PARALLEL WITH A COMMON INPUT-OUTPUT POINT
C     M=7 BELLOWS WITH RELATIVE MOTION BETWEEN THE ENDS
C     M=8 LINE WITH MOUNTING STIFFNESS(OPTION 1)
C     M=9 FORCED CHANGES IN LINE LENGTH
C     M=10 LINE WITH MOUNTING STIFFNESS(OPTION 2)
C     M11 COMPLEX SIDE BRANCH
C     M=12
C     M=13
C     M=14
C     M=15
C     JBNUM=NUMBER OF MATRICES THAT MUST BE SUMMED TO CONSTRUCT MATRIX B
C         B=B(1)+B(2)+...+B(JBNUM)
C     JTERM(J) IS THE NUMBER OF SUBMATRICES IN B(J)
C     K(J,M) IS AN ARRAY THAT DESCRIBES THE TYPE OF MATRICES THAT ARE TO
C      BE MULTIPLIED TOGETHER TO CONSTRUCT THE COMPONENTS OF MATRIX B
C      M TAKES ON VALUES FROM 1 TRHOUGH JTERM(J)
C      FOR EXAMPLE, IF B(2)=D5*D4*C3 THEN K(2,1)=5, K(2,2)=4, K(2,3)=3
C     NGAS=0, NO DISSOLVED GASES IN THE PROPELLANT
C     NGAS=1, DISSOLVED GASES IN PROPELLANT WITH GAS-TO-LIQUID MASS
C       FRACTION, PHI
C     NELAST=0, SPEED OF SOUND IN PROPELLANT IS BASED ON AN INFINITELY
C      RIGID TRANSMISSION LINE
C     NELAST=0, SPEED OF SOUND IN PROPELLANT REFLECTS LINE ELASTICITY
C       (WALL MODULUS EWALL AND WALL THICKNESS HWALL)
C     NEXCITE=NELM PRODUCING THE PRIMARY LINE EXITATION
C     BRCOMP=COMPLIANCE OF SIDE BRANCH ELEMENT
C     BRL=LENGTH OF SIDE BRANCH ELEMENT IN FEET
C     BDIAM=DIAMETER OF SIDE BRANCH ELEMENT IN INCHES
C     BRR=RESISTANCE OF SIDE BRANCH ELEMENT
C     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
      CHARACTER(250) FIN,FOUT
      INTEGER IFIN,IFOUT
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      COMMON BRCOMP,BRL,BRDIAM
C     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *   
C    1 READ 1000
C      IF(EOF,60)5,10
C    5 STOP
C   10 CONTINUE
      PRINT*,'ENTER INPUT FILENAME:'
      READ(*,*) FIN
      IFIN=1
      IFOUT=2
      FIN=TRIM(FIN)
      FOUT=FIN(1:LEN_TRIM(FIN)-3)//"csv"
     
      OPEN(IFIN,FILE=FIN)
      OPEN(IFOUT,FILE=FOUT)
       
      READ (IFIN,*) NELM,JBNUM,NGAS,NELAST,NEXCITE
      READ (IFIN,*) (ITYPE(J),J=1,NELM)
      READ (IFIN,*) (JTERM(J),J=1,JBNUM)
      DO 15 J=1,JBNUM
      KOUNT=JTERM(J)
   15 READ (IFIN,*) (K(J,M),M=1,KOUNT)
      READ (IFIN,*) (BSIGN(J),J=1,JBNUM)
      READ (IFIN,*) HERTZI,DELHZ1,FILIM,DELHZ2,HERTZF
      READ (IFIN,*) SIGN,TERMZ,RHOLIQ,THERMK,P0,T0
      READ (IFIN,*) EWALL,HWALL,ZINPUT,CPCV,BULKMOD,PHI
      READ (IFIN,*) VISC,GASMW,GAMGAS,CP,VMEAN
C     LOOP FOR READ - IN OF LINE ELEMENT DATA
      PI=3.145927
      DO 95 J=1,NELM
      INDEX=ITYPE(J)
      GO TO (20,25,30,35,40,45,50,55,60,65,70,75,80,85,90),INDEX
   20 READ (IFIN,*) EL(J),RADIUS(J)
      AREA(J)=PI*RADIUS(J)**2/144.
      AREA1=AREA(J)
      RAD1=RADIUS(J)/12.
      GO TO 95
   25 READ (IFIN,*) RBUB(J),RADIUS(J)
      GO TO 95
   30 READ (IFIN,*) FPVC(J),AKBPVC(J),AKCPVC(J)
      GO TO 95
   35 GO TO 95
   40 READ (IFIN,*) EL(J),RADIUS(J)
      AREA(J)=PI*RADIUS(J)**2/144.
      GO TO 95
   45 READ (IFIN,*) NPAR
      READ (IFIN,*) (PARLEN(J,I),PARRAD(J,I),I=1,NPAR)
      GO TO 95
   50 READ (IFIN,*) FBEL(J),COMPLY(J),AKBEL(J)
      GO TO 95
   55 READ (IFIN,*) EL(J),RADIUS(J),DAMPER(J),SPRINGK(J)
      AREA(J)=PI*RADIUS(J)**2/144.
      GO TO 95
   60 READ (IFIN,*) EL(J),RADIUS(J),G1,G2,RHOWALL
      AREA(J)=PI*RADIUS(J)**2/144.
      GO TO 95
   65 READ (IFIN,*) EL(J),RADIUS(J),ZX,ZY
      AREA(J)=PI*RADIUS(J)**2/144.
      GO TO 95
   70 READ (IFIN,*) BRL,BRDIAM,BRCOMP
      GO TO 95
   75 READ 1000
      GO TO 95
   80 READ 1000
      GO TO 95
   85 READ 1000
      GO TO 95
   90 READ 1000
      GO TO 95
   95 CONTINUE
C     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  
      G=32.174049
      ETA=(0.,1.)
      IFREQ=1
      FREQ(IFREQ)=HERTZI
C     CALCULATION OF MATRIX ELEMENTS
   99 OMEGA=2.*PI*FREQ(IFREQ)
      DO 175 J=1,NELM
      INDEX=ITYPE(J)
      GO TO (100,105,110,115,120,125,130,135,140,145,150,155,160,165,170
     1),INDEX
  100 CALL ONE
      GO TO 175
  105 CALL TWO
      GO TO 175
  110 CALL THREE
      GO TO 175
  115 CALL FOUR
      GO TO 175
  120 CALL FIVE
      GO TO 175
  125 CALL SIX
      GO TO 175
  130 CALL SEVEN
      GO TO 175
  135 CALL EIGHT
      GO TO 175
  140 CALL NINE
      GO TO 175
  145 CALL TEN
      GO TO 175
  150 CALL ELEVEN
      GO TO 175
  155 CALL TWELVE
      GO TO 175
  160 CALL THIRTEN
      GO TO 175
  165 CALL FOURTEN
      GO TO 175
  170 CALL FIVETEN
  175 CONTINUE
C     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
      CALL DMAT
      CALL BMAT
      ENUM=B(1,1)*(D(2,1)*ZINPUT+D(2,2))-B(2,1)*(D(1,1)*ZINPUT+D(1,2))
      DENOM=D(2,1)*ZINPUT+D(2,2)-(D(1,1)*ZINPUT+D(1,2))/TERMZ  
      TRANS=SIGN*ENUM/DENOM
      SIZE(IFREQ)=CABS(TRANS)
      IF(NEXCITE.EQ.4) GO TO 176
      IF(NEXCITE.EQ.5) GO TO 177
      IF(NEXCITE.EQ.7) GO TO 177
      IF(NEXCITE.EQ.9) GO TO 177
      IF(NEXCITE.EQ.8) GO TO 178
  176 SIZEDB(IFREQ)=20.*ALOG10(SIZE(IFREQ)*AREA1/SQRT(RHOLIQ*BULKMOD))
      GO TO 179
  177 SIZEDB(IFREQ)=20.*ALOG10(SIZE(IFREQ)/SQRT(RHOLIQ*BULKMOD))
      GO TO 179
  178 SIZEDB(IFREQ)=20.*ALOG10(SIZE(IFREQ)/(RHOLIQ*RAD1))
  179 CONTINUE
      ANGLE(IFREQ)=ATAN2(AIMAG(TRANS), REAL(TRANS))*57.29578
  180 ANGLE(IFREQ)=ANGLE(IFREQ)-180.
  185 RADSEC(IFREQ)=OMEGA
      IF(FREQ(IFREQ).LT.HERTZF) GO TO 190
      GO TO 205
  190 IFREQ=IFREQ+1
      IF(FREQ(IFREQ-1)-FILIM) 195,195,200
  195 FREQ(IFREQ)=FREQ(IFREQ-1)+DELHZ1
      IFINAL=IFREQ
      GO TO 99
  200 FREQ(IFREQ)=FREQ(IFREQ-1)+DELHZ2
      IFINAL=IFREQ
      GO TO 99
  205 PRINT 1000
      PRINT 1025
      PRINT 1030
      WRITE(IFOUT,'(39X, A, A)') 'NON-DIMENSIONAL PHASE', ';'
      WRITE(IFOUT,'(10A)') 'OMEGA-RAD/SEC', ';','FREQ-HZ',';',
     1'TRANS-P/K',';','TRANS-DB',';','ANGLE-DEG',';'
      DO 250 I=1,IFINAL
      WRITE(IFOUT,'(F9.1,A,F15.1,A,F13.3,A,F14.2,A,F15.1,A)') RADSEC(I),
     1';',FREQ(I),';',SIZE(I),';',SIZEDB(I),';',ANGLE(I),';'
  250 PRINT 1040,RADSEC(I),FREQ(I),SIZE(I),SIZEDB(I),ANGLE(I)
C      GO TO 1
C     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 1000 FORMAT(55H1111111111111111111111111111111111111111111111111111111)
 1005 FORMAT(24I3)
 1020 FORMAT(6E12.6)
 1025 FORMAT(1H0,39X,15HNON-DIMENSIONAL,5X,5HPHASE)
 1030 FORMAT(14H OMEGA-RAD/SEC,4X,7HFREQ-HZ,4X,9HTRANS-P/K,6X,8HTRANS-DB
     1,6X,9HANGLE-DEG)
 1040 FORMAT(1X,F9.1,F15.1,F13.3,F14.2,F15.1)
 1050 FORMAT(1H1,E14.6,6E15.6)
      END
      
      SUBROUTINE ONE
C     THIS SUBROUTINE CALCULATED THE ELEMENTS OF THE TRANSFER MATRIX FOR A
C     STRAIGHT LINE OF LENGTH L WITHOUT EXTERNAL EXCITATION
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      COMMON BRCOMP,BRL,BRDIAM
      CALL SPEED
      REYNOLD=VMEAN*2.*RADIUS(J)/(ENU*12.)
      RT=144.*(2*ENU*0.0055*REYNOLD**0.85)/(RADIUS(J)**2)
      Z1=(OMEGA*EL(J)*ETA)/C0
      Z2=CSQRT((1.,0.)+RT/(OMEGA*ETA))
      XI=SQRT(OMEGA/ENU)*CSQRT(-ETA)
      ARG=XI*RADIUS(J)/12.
      CALL J1ORJ0(ARG,RJ)                                        
      GAMMA=ETA*OMEGA*EL(J)/(C0*CSQRT((1.,0.)-2.*RJ/ARG))+REAL(Z1*Z2)
      ZC=RHO0*C0/(CSQRT((1.,0)-2.*RJ/ARG))                            
      COSHG=(CEXP(GAMMA)+CEXP(-GAMMA))/2.
      SINHG=(CEXP(GAMMA)-CEXP(-GAMMA))/2.
      DD(1,1,J)=COSHG
      DD(1,2,J)=-ZC*SINHG/AREA(J)
      DD(2,1,J)=-AREA(J)*SINHG/ZC
      DD(2,2,J)=COSHG
      RETURN
      END
      
      SUBROUTINE TWO
C     THIS SUBROUTINE CALCULATES THE COMPLIANCE OF AND TRANSFER MATRIX
C     ACROSS A SINGLE BUBBLE
C     CPCV=RATIO OF SPECIFIC HEATS FOR THE GAS IN THE BUBBLE
C     CP=SPECIFIC HEAT AT CONSTANT PRESSURE FOR THEGAS IN THE BUBBLE
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      GASCON=778.*CP*(1.-1./CPCV)
      GASDEN=144.*P0/(GASCON*G*(T0+460.))
      DTHERM=THERMK/(GASDEN*CP*G)
      PR0=SQRT(OMEGA*3600./(2.*DTHERM))*RBUB(J)/12.
C     IF(PR0.GT.35.)20,10
      IF(PR0.GT.35.) THEN
          GO TO 20
      ELSE
          GO TO 10
      END IF
   10 T1=(SINH(2.*PR0)+SIN(2.*PR0))/(COSH(2.*PR0)-COS(2.*PR0))
      T2=(SINH(2.*PR0)-SIN(2.*PR0))/(COSH(2.*PR0)-COS(2.*PR0))
      T3=2.*PR0/(3.*(CPCV-1.))
      T4=(T1-1./PR0)/(T3+T2)
      POLY=CPCV/((1.+T2/T3)*(1.+T4**2))
      GO TO 30
   20 POLY=CPCV
   30 BUBVOL=4.*PI*RBUB(J)**3/(3.*1728.)
      CALL SPEED
      SPRING=POLY*P0*144./BUBVOL
      AMASS2=RHO0/(4.*PI*RBUB(J)/12.)
C     IF(PRO.GT.35.)50,40
      IF(PR0.GT.35.) THEN
          GO TO 50
      ELSE
          GO TO 40
      END IF
   40 BTHERM=T4*SPRING/OMEGA
      GO TO 60
   50 BTHERM=3.*(CPCV-1.)*SPRING/(2.*PR0*OMEGA)
   60 BRAD=AMASS2*RBUB(J)*(OMEGA**2)/(12.*C0)
      BVIS=1728.*VISC/(PI*RBUB(J)**3)
      BDAMP=BTHERM+BRAD+BVIS
      DD(1,1,J)=(1.,0.)
      DD(1,2,J)=(0.,0.)
      DD(2,1,J)=-ETA*OMEGA/(-AMASS2*OMEGA**2+ETA*BDAMP*OMEGA+SPRING)
      DD(2,2,J)=(1.,0)
      RETURN
      END
 
      SUBROUTINE THREE
C     THIS SUBROUTINE CALCULATES THE TRANSFER MATRIX FOR A PRESSURE-
C     VOLUME COMPENSATOR(PVC JOINT)
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      FRICT=FPVC(J)
      AKB=AKBPVC(J)
      AKC=AKCPVC(J)
      AKPVC=AKB-AKC
      DD(1,1,J)=FRICT
      DD(1,2,J)=(0.,0.)
      DD(2,1,J)=(0.,0.)
      DD(2,2,J)=(1.,0.)
      CC(1,1,J)=(0.,0.)
      CC(2,1,J)=AKPVC
      RETURN
      END
      
      SUBROUTINE FOUR
C     THIS SUBROUTINE CALCULATES THE ELEMENTS OF THE TRANSFER MATRIX FOR
C     A SIDE BRANCH PULSER
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      DD(1,1,J)=(1.,0)
      DD(1,2,J)=(0.,0.)
      DD(2,1,J)=(0.,0.)
      DD(2,2,J)=(1.,0.)
      CC(1,1,J)=(0.,0.)
      CC(2,1,J)=(1.,0.)
      RETURN
      END
      
      SUBROUTINE FIVE
C     THIS SUBROUTINE CALCULATES THE ELEMENTS OF THE TRANSFER MATRIX 
C     FOR THE LONGITUDINAL RIGID BODY MOTION OF A SIMPLE LINE OF LENGHT
C     L. THE MOTION IS A RESULT OF VELOCITY EXITATION
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      CALL SPEED
      REYNOLD=VMEAN*2.*RADIUS(J)/(ENU*12.)
      RT=144.*(2*ENU*0.0055*REYNOLD**0.85)/(RADIUS(J)**2)
      Z1=(OMEGA*EL(J)*ETA)/C0
      Z2=CSQRT((1.,0.)+RT/(OMEGA*ETA))
      XI=SQRT(OMEGA/ENU)*CSQRT(-ETA)
      ARG=XI*RADIUS(J)/12.
      CALL J1ORJ0(ARG,RJ)                                        
      GAMMA=ETA*OMEGA*EL(J)/(C0*CSQRT((1.,0.)-2.*RJ/ARG))+REAL(Z1*Z2)
      ZC=RHO0*C0/(CSQRT((1.,0)-2.*RJ/ARG))                            
      COSHG=(CEXP(GAMMA)+CEXP(-GAMMA))/2.
      SINHG=(CEXP(GAMMA)-CEXP(-GAMMA))/2.
      DD(1,1,J)=COSHG
      DD(1,2,J)=-ZC*SINHG/AREA(J)
      DD(2,1,J)=-AREA(J)*SINHG/ZC
      DD(2,2,J)=COSHG
      CC(1,1,J)=ZC*SINHG
      CC(2,1,J)=AREA(J)*((1.,0.)-COSHG)
      
      RETURN 
      END

      SUBROUTINE SIX
C     THIS SUBROUTINE CALCULATES THE ELEMENTS OF THE TRANSFER MATRIX FOR
C     AN ARBITRARY NUMBER OF LINES IN PARALLEL ALL OF WHICH EMANATE FROM
C     AND CONVERGE ON COMMON INPUT-OUTPUT POINTS
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      DO 5 I=1,NPAR
      CALL SPEED
      C0=C0/SQRT(1.+BULKMOD*2.*PARRAD(J,I)/(144.*EWALL*HWALL))
      SQFT=PI*PARRAD(J,I)**2/144.
      XI=SQRT(OMEGA/ENU)*CSQRT(-ETA)
      ARG=XI*PARRAD(J,I)/12.
      CALL J1ORJ0(ARG,RJ)
      GAMMA=ETA*OMEGA*PARLEN(J,I)/(C0*CSQRT((1.,0.)-2.*RJ/ARG))
      ZC=RHO0*C0/(CSQRT((1.,0.)-2.*RJ/ARG))
      COSHG=(CEXP(GAMMA)+CEXP(-GAMMA))/2.
      SINHG=(CEXP(GAMMA)-CEXP(-GAMMA))/2.
      TCOTH=TCOTH+SQFT*COSHG/(SINHG*ZC)
    5 TCSCH=TCSCH+SQFT/(ZC*SINHG)
      DD(1,1,J)=TCOTH/TCSCH
      DD(1,2,J)=-1./TCSCH
      DD(2,1,J)=TCSCH-TCOTH**2/TCSCH
      DD(2,2,J)=TCOTH/TCSCH      
      RETURN 
      END

      SUBROUTINE SEVEN
C     THIS SUBROUTINE CALCULATES THE ELEMENTS OF THE TRANSFER MATRIX FOR
C     A BELLOWS WITH A LUMPED COMPLIANCE REPRESENTING TRAPPED GAS UNDER
C     THE LINER PLUS A PERIODIC VOLUMETRIC CHANGE DUE TO RELATIVE MOTION
C     OF THE ENDS OF THE BELLOWS
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      FRICT=FBEL(J)
      C=COMPLY(J)
      AKB=AKBEL(J)
      DD(1,1,J)=FRICT
      DD(1,2,J)=(0.,0.)
      DD(2,1,J)=-C*ETA*OMEGA
      DD(2,2,J)=(1.,0.)
      CC(1,1,J)=(0.,0.)
      CC(2,1,J)=AKB
      RETURN
      END

      SUBROUTINE EIGHT
C     THIS SUBROUTINE CALCULATES THE ELEMENTS OF THE TRANSFER MATRIX 
C     FOR  THE AXIAL MOTION OF A VERTICAL LINE WITH MOUNTING STIFFNESS
C     ON THE TWO ADJACENT HORISONTAL LINES. THE TWO STIFNESS TERMS ARE
C     LUMPED INTO ONE EFFECTIVE SPRING IN PARALLEL WITH ONE EFFECTIVE
C     VISCOUS DAMPER. THE FORCING FUNCTION IS AN ACCELERATION APPLIED 
C     TO THE SPRING-DAMPER SUPPORT PLUS A PASSIVE INERTIAL LOADING
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      CALL SPEED
      REYNOLD=VMEAN*2.*RADIUS(J)/(ENU*12.)
      RT=144.*(2*ENU*0.0055*REYNOLD**0.85)/(RADIUS(J)**2)
      Z1=(OMEGA*EL(J)*ETA)/C0
      Z2=CSQRT((1.,0.)+RT/(OMEGA*ETA))
      XI=SQRT(OMEGA/ENU)*CSQRT(-ETA)
      ARG=XI*RADIUS(J)/12.
      CALL J1ORJ0(ARG,RJ)                                        
      GAMMA=ETA*OMEGA*EL(J)/(C0*CSQRT((1.,0.)-2.*RJ/ARG))+REAL(Z1*Z2)
      ZC=RHO0*C0/(CSQRT((1.,0)-2.*RJ/ARG))                            
      COSHG=(CEXP(GAMMA)+CEXP(-GAMMA))/2.
      SINHG=(CEXP(GAMMA)-CEXP(-GAMMA))/2.
      AMASS=RHO0*(AREA(J-1)*EL(J-1)+AREA(J+1)*EL(J+1))
      QUADRAT=-AMASS*OMEGA**2+ETA*OMEGA*DAMPER(J)+SPRINGK(J)
      ALPHAP=(ETA*OMEGA*DAMPER(J)+SPRINGK(J))*ZC*SINHG/(QUADRAT*ETA*OMEG
     1A)
      BETAP=AREA(J)*ETA*OMEGA*ZC*SINHG/QUADRAT
      ALPHADP=(ETA*OMEGA*DAMPER(J)+SPRINGK(J))*AREA(J)*((1.,0.)-COSHG)/(
     1ETA*OMEGA*QUADRAT)
      BETADP=(AREA(J)**2)*ETA*OMEGA*((1.,0.)-COSHG)/QUADRAT
      DD(1,1,J)=(COSHG+BETAP)/(1.+BETAP)
      DD(1,2,J)=-ZC*SINHG/(AREA(J)*(1.+BETAP))
      DD(2,1,J)=-AREA(J)*SINHG/ZC+BETADP*((1.,0.)-COSHG)/(1.+BETAP)
      DD(2,2,J)=COSHG+BETADP*ZC*SINHG/(AREA(J)*(1.+BETAP))
      CC(1,1,J)=ALPHAP/(1.+BETAP)      
      CC(2,1,J)=ALPHADP/(1.+BETAP)
      RETURN
      END

      SUBROUTINE NINE
C     THIS SUBROUTINE CALCULATES THE ELEMENTS OF THE TRANSFER MATRIX 
C     FOR  A LINE WITH FORCED CHANGES IN LINE LENGTH
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      GOFS=G1+G2*ETA
      CW=SQRT((EWALL*G)/(RHOWALL*12.))      
      CALL SPEED
      REYNOLD=VMEAN*2.*RADIUS(J)/(ENU*12.)
      RT=144.*(2*ENU*0.0055*REYNOLD**0.85)/(RADIUS(J)**2)
      Z1=(OMEGA*EL(J)*ETA)/C0
      Z2=CSQRT((1.,0.)+RT/(OMEGA*ETA))
      XI=SQRT(OMEGA/ENU)*CSQRT(-ETA)
      ARG=XI*RADIUS(J)/12.
      CALL J1ORJ0(ARG,RJ)                                        
      GAMMA=ETA*OMEGA*EL(J)/(C0*CSQRT((1.,0.)-2.*RJ/ARG))+REAL(Z1*Z2)
      ZC=RHO0*C0/(CSQRT((1.,0)-2.*RJ/ARG))                            
      COSHG=(CEXP(GAMMA)+CEXP(-GAMMA))/2.
      SINHG=(CEXP(GAMMA)-CEXP(-GAMMA))/2.
      DD(1,1,J)=COSHG
      DD(1,2,J)=-ZC*SINHG/AREA(J)
      DD(2,1,J)=-AREA(J)*SINHG/ZC
      DD(2,2,J)=COSHG
      SLCW=ETA*OMEGA*EL(J)/CW
      COSHCW=(CEXP(SLCW)+CEXP(-SLCW))/2.
      SINHCW=(CEXP(SLCW)-CEXP(-SLCW))/2.
      COEFF=(-OMEGA**2/C0**2-(GAMMA/EL(J))**2)/(-OMEGA**2/CW**2-(GAMMA/E
     1L(J))**2)
      ALPHA1=(RHO0*C0**2/(ETA*OMEGA))*((ETA*OMEGA*SINHCW/CW-GAMMA*SINHG/
     1EL(J))+(GOFS-COSHCW)*(COSHCW-COSHG)*ETA*OMEGA/(CW*SINHCW))
      ALPHA2=-((COSHCW-COSHG)+(GOFS-COSHCW)*(SINHCW-ETA*OMEGA*EL(J)*SINH
     1G/(CW*GAMMA))/SINHCW)
      CC(1,1,J)=COEFF*ALPHA1     
      CC(2,1,J)=COEFF*ALPHA2*AREA(J) 
      RETURN
      END

      SUBROUTINE TEN
C     THIS SUBROUTINE CALCULATES THE ELEMENTS OF THE TRANSFER MATRIX 
C     FOR THE AXIAL MOTION OF A VERTICAL LINE WITH MOUNTING STIFFNESS.
C     THE STIFFNESS IS REPRESENTED BY THE IMPEDANCE PRESENTED TO THE 
C     LINE BY THE VEHICLE STRUCTURE.
C     THIS SUBROUTINE CAN BE USED ONLY WHEN ANOTHER SOURCE OF EXITATION
C     IS PRESENT IN THE FEEDLINE, I.E. PULSER OR VERTICAL LINE VELOCITY
C     EXITATION. THE FUNCTIONAL FORM OF THE STRUCTURAL IMPEDANCE IS
C     THAT OF AN EQUIVALENT SPRING AND DASHPOT IN PARALLEL.
C     ZX AND ZY ARE THE REAL AND IMAGINARY PARTS OF ZSTRUCT.
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      CALL SPEED
      REYNOLD=VMEAN*2.*RADIUS(J)/(ENU*12.)
      RT=144.*(2*ENU*0.0055*REYNOLD**0.85)/(RADIUS(J)**2)
      Z1=(OMEGA*EL(J)*ETA)/C0
      Z2=CSQRT((1.,0.)+RT/(OMEGA*ETA))
      XI=SQRT(OMEGA/ENU)*CSQRT(-ETA)
      ARG=XI*RADIUS(J)/12.
      CALL J1ORJ0(ARG,RJ)                                        
      GAMMA=ETA*OMEGA*EL(J)/(C0*CSQRT((1.,0.)-2.*RJ/ARG))+REAL(Z1*Z2)
      ZC=RHO0*C0/(CSQRT((1.,0)-2.*RJ/ARG))                            
      COSHG=(CEXP(GAMMA)+CEXP(-GAMMA))/2.
      SINHG=(CEXP(GAMMA)-CEXP(-GAMMA))/2.
      AMASS=RHO0*(AREA(J-1)*EL(J-1)+AREA(J+1)*EL(J+1))
      ZSTRUCT=ZX-ETA*ZY/OMEGA
      ALPHA=AREA(J)*ZC*SINHG/(ZSTRUCT+AMASS*ETA*OMEGA)
      BETA=(1.-COSHG)*(AREA(J)**2)/(ZSTRUCT+AMASS*ETA*OMEGA)
      DD(1,1,J)=(COSHG+ALPHA)/(1.+ALPHA)
      DD(1,2,J)=-ZC*SINHG/(AREA(J)*(1.+ALPHA))
      DD(2,1,J)=-AREA(J)*SINHG/ZC+BETA*(1.-COSHG)/(1.+ALPHA)
      DD(2,2,J)=COSHG+ZC*SINHG*BETA/(AREA(J)*(1.+ALPHA))
      RETURN
      END
      
      SUBROUTINE ELEVEN
C     THIS SUBROUTINE CALCULATES THE ELEMENTS OF THE TRANSFER 
C     MATRIX  FOR A COMPLEX SIDE BRANCH. THIS MODEL ASSUMES A
C     LAMINAR FLOW IN THE SIDE BRANCH.
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      COMMON BRCOMP,BRL,BRDIAM
      COMPLEX S
      S=ETA*OMEGA
   10 CALL SPEED
      AREAB=(PI/4.)*(BRDIAM/12.)**2
      BRI=RHO0*BRL/AREAB
      BRR=128.*VISC*BRL/(PI*(BRDIAM/12.)**4.)
      DD(1,1,J)=(1.,0)
      DD(1,2,J)=(0.,0.)
      DD(2,1,J)=-S*BRCOMP/(BRI*BRCOMP*S**2+BRR*BRCOMP*S+1.)
      DD(2,2,J)=(1.,0.)
      RETURN
      END
      
      SUBROUTINE TWELVE
      END
      
      SUBROUTINE THIRTEN
      END
      
      SUBROUTINE FOURTEN
      END
      
      SUBROUTINE FIVETEN
      END
      
      SUBROUTINE SPEED
C     THIS SUBROUTINE CALCULATES THE SPEED OF SOUND FOR THE FLUID IN THE
C     FEEDLINE. THIS FLUID MAY BE A LIQUID OR A HOMOGENEOUS MIXTURE OF
C     A LIQUID AND ULLAGE GAS
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      CLIQUID=SQRT(BULKMOD/RHOLIQ)
C      IF(NGAS.EQ.1)10,20
      IF(NGAS.EQ.1) THEN
          GO TO 10
      ELSE
          GO TO 20
      END IF
   10 RHOGAS=144.*P0*GASMW/(1545.*(T0+460.)*G)
      CGAS=SQRT(GAMGAS*G*1545.*(T0+460.)/GASMW)
      E1=RHOGAS+PHI*RHOLIQ
      E2=RHOGAS/(RHOLIQ*CLIQUID**2*E1)+(PHI*RHOLIQ)/(E1*RHOGAS*CGAS**2)
      E3=(1.+PHI)*RHOGAS*RHOLIQ
      C0=SQRT(E1/(E2*E3))
      RHO0=E3/E1
      ENU=VISC/RHO0
      GO TO 30
   20 C0=CLIQUID
      RHO0=RHOLIQ
      ENU=VISC/RHO0
C  30 IF(NELAST.EQ.1)40,50
   30 IF(NELAST.EQ.1) THEN
          GO TO 40
      ELSE
          GO TO 50
      END IF
   40 C0=C0/SQRT(1.+C0**2*RHO0*2.*(RADIUS(J)+HWALL)/(144.*EWALL*HWALL))
   50 RETURN
      END


      SUBROUTINE DMAT
C     THIS SUBROUTINE CALCULATES MATRIX D IN THE EXPRESSION P=DQ+VB
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      DO 10 M=1,2
      DO 10 N=1,2
   10 D(M,N)=DD(M,N,1)
      IF(NELM-1)50,20,30
   20 RETURN
   30 DO 40 J=2,NELM
      X1=DD(1,1,J)*D(1,1)+DD(1,2,J)*D(2,1)
      X2=DD(1,1,J)*D(1,2)+DD(1,2,J)*D(2,2)
      X3=DD(2,1,J)*D(1,1)+DD(2,2,J)*D(2,1)
      X4=DD(2,1,J)*D(1,2)+DD(2,2,J)*D(2,2)
      D(1,1)=X1
      D(1,2)=X2
      D(2,1)=X3
   40 D(2,2)=X4
      RETURN
   50 PRINT 60
      CALL EXIT
   60 FORMAT(28H0ERROR IN NELM SPECIFICATION)
      END

      SUBROUTINE BMAT
C     THIS SUBROUTINE CALCULATES MATRIX B IN THE EXPRESSION P=DQ+VB
      COMPLEX ETA,ENUM,DENOM,TRANS,B,D,XI,ARG,RJ,GAMMA,ZC,COSHG,SINHG,DD
     1,CC,TCOTH,TCSCH,BB,Z1,Z2,X1,X2,X3,X4,QUADRAT,ALPHAP,BETAP,ALPHADP,
     2BETADP,GOFS,SLCW,COSHCW,SINHCW,COEFF,ALPHA1,ALPHA2
      COMPLEX ZSTRUCT,ALPHA,BETA
      DIMENSION ITYPE(15),JTERM(15),K(15,15),EL(15),RADIUS(15),RBUB(15),
     1FPVC(15),AKBPVC(15),AKCPVC(15),PARLEN(15,5),PARRAD(15,5),FREQ(200)
      DIMENSION B(2,1),D(2,2),SIZE(200),SIZEDB(200),ANGLE(200),FBEL(15),
     1COMPLY(15),AKBEL(15),BSIGN(10),DAMPER(15),SPRINGK(15)
      DIMENSION DD(2,2,15),CC(2,1,15),BB(2,1,15),RADSEC(200),AREA(15)
      COMMON PI,RADIUS,OMEGA,ENU,ETA,EL,C0,RHO0,THERMK,RBUB,CPCV,P0,VISC
     1,FPVC,AKBPVC,AKCPVC,NPAR,PARRAD,PARLEN,BULKMOD,RHOLIQ,NGAS,GASMW
      COMMON GAMGAS,G,T0,PHI,COMPLY,NELAST,EWALL,HWALL,NELM,JBNUM,JTERM,
     1K,DD,CC,D,B,BB,CP,J,AREA,VMEAN,FBEL,AKBEL,BSIGN,DAMPER,SPRINGK
      COMMON G1,G2,RHOWALL,ZX,ZY
      DO 100 I=1,JBNUM
      KOUNT=JTERM(I)
      L=K(I,KOUNT)
      DO 100 J=1,KOUNT
      IF(J-1)5,5,15
    5 DO 10 M=1,2
   10 BB(M,1,I)=CC(M,1,L)
      GO TO 100
   15 L=K(I,KOUNT-J+1)
      X1=DD(1,1,L)*BB(1,1,I)+DD(1,2,L)*BB(2,1,I)
      X2=DD(2,1,L)*BB(1,1,I)+DD(2,2,L)*BB(2,1,I)
      BB(1,1,I)=X1
      BB(2,1,I)=X2
  100 CONTINUE
      B(1,1)=BSIGN(1)*BB(1,1,1)
      B(2,1)=BSIGN(1)*BB(2,1,1)
  110 DO 200 M=1,2
      DO 200 I=2,JBNUM
  200 B(M,1)=B(M,1)+BSIGN(I)*BB(M,1,I)
  210 RETURN
      END
      
      SUBROUTINE J1ORJ0(Z,RJ)
C     CALCULATION OF J0(Z) AND J1(Z) Z-COMPLEX
      COMPLEX Z,J1,J0,TERM0,TERM1,Z1,Z2,P0,Q0,P1,Q1,PH0,PH1,FZ1,FZ2,RJ
      X=REAL(Z)
      Y=AIMAG(Z)
      R=CABS(Z)
      IF(R-18.)100,100,110
  100 TERM1=Z/2
      J1=Z/2
      J0=(1.,0.)
      TERM0=(1.,0.)
      A=1.
      AM=15.+R
  101 TERM0=TERM0*(-(Z/2.)**2)/A**2
      J0=J0+TERM0
      TERM1=TERM1*(-(Z/2.)**2)/((A+1.)*A)
      J1=J1+TERM1
      A=A+1.
      IF(A-AM)101,101,115
  110 IF(X)111,112,112
  111 Z1=-Z
      GO TO 113
  112 Z1=Z
  113 PI=3.1415926
      Z2=8.*Z1
      IF(CABS(Z2)-5000.)120,120,121
  120 P0=(1.,0.)-4.5/Z2**2+3675./(8.*Z2**4)
      Q0=-1./Z2+37.5/Z2**3-59535./(8.*Z2**5)
      P1=(1.,0.)+7.5/Z2**2-4725./(8.*Z2**4)
      Q1=3./Z2-52.5/Z2**3+72765./(8.*Z2**5)
      GO TO 122
  121 P0=(1.,0.)-4.5/Z2**2
      Q0=-1./Z2
      P1=(1.,0.)+7.5/Z2**2
      Q1=3./Z2
  122 PH0=Z1-PI/4.
      PHI=Z1-.75*PI
      FZ1=2./(PI*Z1)
      FZ2=CSQRT(FZ1)
      AZ1=AIMAG(Z1)
      IF(ABS(AZ1)-50.)116,116,117
  116 J0=FZ2*(P0*CCOS(PH0)-Q0*CSIN(PH0))
      J1=FZ2*(P1*CCOS(PH1)-Q1*CSIN(PH1))
      IF(X)114,115,115
  114 J1=-J1
  115 RJ=J1/J0
      GO TO 119
  117 SIN=Y/ABS(Y)
      RJ=(SIN*(0.,1.)*P1+Q1)/(P0-SIN*(0.,1.)*Q0)
  119 RETURN
      END
      
      